openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
  description: Sample API using Swagger
servers:
  - url: http://localhost:5000
    description: Local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /api/v1/users/login:
    post:
      summary: Get data from a protected route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
  /api/v1/users/register:
    post:
      summary: Get data from a protected route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  format: text
                  description: User's email address
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
  /api/v1/users:
    get:
      summary: Get data from a protected route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
  /api/v1/entries:
    get:
      summary: Get data from a protected route
      parameters:
        - in: query
          name: Category
          schema:
            type: string
          description: Page number for pagination (default is 1)
        - in: query
          name: limit
          schema:
            type: integer
          description: Page number for pagination (default is 1)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
  /api/v1/posts:
    get:
      summary: Get data from a protected route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Response message
